name: Build Android App with Expo EAS

on:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: expo/expo-github-action@v6
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    - name: Install npm dependencies
      run: npm install
    - name: Install expo-dev-client
      run: expo install expo-dev-client
    - run: eas build --platform android --profile development --non-interactive
